name: TimePerDayWhitelist
version: '${project.version}'
main: gg.vynofc.timeperday.TimePerDayPlugin
api-version: '1.21'
description: Begrenzt die tägliche Spielzeit pro Spieler
authors: [ niliees ]
folia-supported: true

commands:
  admintime:
    description: Verwalte Zeit, Level und globale Resets
    usage: /admintime <subcommand>
    permission: timeperday.admin
    aliases: [ timeperday, tpd ]
  time:
    description: Zeigt die verbleibende Spielzeit für den Tag an
    usage: /time
    permission: timeperday.use
  debugtime:
    description: Debug-Events manuell auslösen (z. B. Tageswechsel)
    usage: /debugtime <dayover|warn|timeout>
    permission: timeperday.debug

permissions:
  timeperday.admin:
    description: Zugriff auf alle TimePerDay-Befehle
    default: op
  timeperday.bypass:
    description: Umgeht das tägliche Spielzeitlimit (wie Whitelist)
    default: false
  timeperday.use:
    description: Zugriff auf die TimePerDay-Funktionalität
    default: true
  timeperday.debug:
    description: Zugriff auf Debug-Events für TimePerDay
    default: op
