name: TimePerDayWhitelist
version: '${project.version}'
main: fun.vynofc.timeperday.TimePerDayPlugin
api-version: '1.21'
description: Begrenzt die tägliche Spielzeit pro Spieler
authors: [ vynOFC ]
website: https://vynofc.fun
folia-supported: true

commands:
  tpdadmin:
    description: Verwalte Zeit, Level und globale Resets
    usage: /tpdadmin <subcommand>
    permission: timeperday.admin
  tpd:
    description: Zeigt die verbleibende Spielzeit und Einstellungen an
    usage: /tpd [time|settings]
    permission: timeperday.use
  tpddebug:
    description: Debug-Events manuell auslösen (z. B. Tageswechsel)
    usage: /tpddebug <dayover|warn|timeout>
    permission: timeperday.debug

permissions:
  timeperday.admin:
    description: Zugriff auf alle TimePerDay-Befehle
    default: op
  timeperday.bypass:
    description: Umgeht das tägliche Spielzeitlimit (wie Whitelist)
    default: false
  timeperday.use:
    description: Zugriff auf die TimePerDay-Funktionalität
    default: true
  timeperday.debug:
    description: Zugriff auf Debug-Events für TimePerDay
    default: op


